# Generated by Django 4.0.5 on 2022-09-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Turbat', 'Turbat'), ('Gwadar', 'Gwadar'), ('Pasni', 'Pasni'), ('Panjgoor', 'Panjgoor'), ('Jewani', 'Jewani'), ('Keach', 'Keach'), ('Sibi', 'Sibi'), ('DG khan', 'DG khan'), ('Tump', 'Tump')], max_length=100)),
            ],
        ),
    ]
