# Generated by Django 4.0.5 on 2022-09-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_musician_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(choices=[('Turbat', 'Turbat'), ('Gwadar', 'Gwadar'), ('Pasni', 'Pasni'), ('Panjgoor', 'Panjgoor'), ('Jewani', 'Jewani'), ('Keach', 'Keach'), ('Sibi', 'Sibi'), ('DG khan', 'DG khan'), ('Tump', 'Tump')], max_length=100),
        ),
    ]
