# Generated by Django 4.0.5 on 2022-09-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_musician_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Turbat', 'Turbat'), ('Gwadar', 'Gwadar'), ('Pasni', 'Pasni'), ('Panjgoor', 'Panjgoor'), ('Jewani', 'Jewani'), ('Keach', 'Keach'), ('Sibi', 'Sibi'), ('DG khan', 'DG khan'), ('Tump', 'Tump')], max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
