# Generated by Django 4.0.5 on 2022-09-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_musician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumerDetail',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
    ]
