# Generated by Django 4.0.5 on 2022-09-20 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_delete_costumerdetail_remove_musician_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Turbat', 'Turbat'), ('Gwadar', 'Gwadar'), ('Pasni', 'Pasni'), ('Panjgoor', 'Panjgoor'), ('Jewani', 'Jewani'), ('Keach', 'Keach'), ('Sibi', 'Sibi'), ('DG khan', 'DG khan'), ('Tump', 'Tump')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
